name: CI

on: [ push , pull_request ]

jobs:
  make_xml:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: create xml files
      run: python scripts/csv2xml.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
